jdz:
  D2WC: null
spring:
  datasource:
    url: jdbc:postgresql:testDB
    username: test
    password: test
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: false
      hibernate:
        ddl-auto: none
        cache.use_second_level_cache: false
        use_query_cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false